### ISSUE TITLE
How to make borders thinner?

### ISSUE THREAD

**Issue by fomines** [Apostolique/Apos.Shapes#4]
Hello!
Thank you for your work and your library.
When I draw:
  _sb.DrawCircle(new Vector2(120, 120), 75, new Color(96, 165, 250), new Color(191, 219, 254), 1f);
I still have a thick border that I would like to make much thinner.
Decreasing 0.1f for thickness has no effect.
Is it possible to make the border lines thinner? Thank you!

**Comment by Apostolique** [comment]
It's possible but you'd have to modify the shader. You can try version 0.1.10 to see if you prefer that. The lines were thinner in that version at the cost of color accuracy for the line.

**Comment by Apostolique** [comment]
Can you try version 0.2.1? I just released a change to the border computation.

**Comment by Apostolique** [comment]
I'll assume that the latest version fixed this. Feel free to comment against if that's not the case.

**Comment by Apostolique** [comment]
I guess one issue is figuring out what a thickness value means. For example, in Figma setting a border at 0.2 gives this kind of result:
![image](https://github.com/Apostolique/Apos.Shapes/assets/2766423/41995b11-f254-4a65-b6de-9e8be4095d25)

0.5:
![image](https://github.com/Apostolique/Apos.Shapes/assets/2766423/46761aae-cff8-45f6-89cc-6786b78a61bd)

1:
![image](https://github.com/Apostolique/Apos.Shapes/assets/2766423/4f917357-edf6-464b-af5c-974308b9494b)

**Comment by fomines** [comment]
Yes, I have the same dimensions in Figma. But if this line is drawn using Apos.Shapes with a thickness of 1, it looks thicker than in Figma. That is, the minimum thickness that can be set is greater than thickness 1 in Figma. That's why I wrote about relative thickness. Is it possible to make it a little thinner to implement Figma's scale for thickness = 1 or even thinner?

**Comment by AndreyPalyutin** [comment]
Hi all,
i second this question.
This is the thinnest borders i have with Apos.Shapes:
![image](https://github.com/Apostolique/Apos.Shapes/assets/135964729/1e9dbce5-ac97-4750-bb3a-b8cc106ddab1)
But i'd like to have them as thin as the vertical grey line next to the circles.

Would really appreciate if you could implement this in the next release.

**Comment by Apostolique** [comment]
I just pushed a new version that allows setting your own aaSize as an optional argument. Play with the values to find what you like, but as a start you can try with a thickness of `0.7f` and an aaSize of `1.1f`. I found those values to look quite thin.

You can think of the anti-aliasing size as a blur factor. It determines how smooth a shape's edge should look.

**Comment by AndreyPalyutin** [comment]
This is exactly what i needed, works perfect to me!
Many many thanks!

**Comment by Apostolique** [comment]
Cool!
