### ISSUE TITLE
Exception when create shapebatch

### ISSUE THREAD

**Issue by segatecm** [Apostolique/Apos.Shapes#9]
protected override void LoadContent()
 {
     _graphics.GraphicsProfile = GraphicsProfile.HiDef;
     _spriteBatch = new SpriteBatch(GraphicsDevice);
     ShapeBatch _sb = new ShapeBatch(GraphicsDevice, Content);  // Exception!!!
     // TODO: use this.Content to load your game content here
 }

It report:
SharpDX.SharpDXException: 'HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: 参数错误。

I copy the spos-shapes.fx file to the content.mgcb and compile it.

I install the monogame with nuget. 
VS: 2022
Monogame : 3.8.1.303
Apos.Shapes : 0.3.0

**Comment by Apostolique** [comment]
Try to add this line:

```cs
_graphics.GraphicsProfile = GraphicsProfile.HiDef;
_graphics.ApplyChanges();
```

**Comment by segatecm** [comment]
It works!
 _graphics.GraphicsProfile = GraphicsProfile.HiDef;  //must call with ApplyChanges().
Thanks!

**Comment by Apostolique** [comment]
You can check the example project https://github.com/Apostolique/Apos.Shapes/blob/1a6c92e6fa0c32c0f0d18a3de162366557883215/Example/Game/GameRoot.cs#L12-L17

I tend to place that line in the game's constructor since I don't need to call ApplyChanges from there.

**Comment by segatecm** [comment]
Yes, you are right.
 this statement must be placed inside the constructor. If the ApplyChanges function is called, it must be before ApplyChanges.
